### ISSUE TITLE
Timestamping but ignore files older than?

### ISSUE THREAD

**Issue by kenorb** [jay/wget#1]
I'm requesting feature which was proposed some time ago in the mailing list: [Timestamping but ignore files older than?](https://www.mail-archive.com/wget@sunsite.dk/msg09667.html), so I'm not sure if it's tracked somewhere else.

See also: [Using wget to target files within a date range](http://unix.stackexchange.com/q/119136/21471) at Unix SE

**Comment by jay** [comment]
This isn't the wget repo it's my fork. If you have a feature concern ask about it on the bug-wget mailing list https://www.gnu.org/software/wget/manual/html_node/Mailing-Lists.html#Mailing-Lists
