### ISSUE TITLE
Export history file

### ISSUE THREAD

**Issue by vendforce** [jay/wget#3]
I want to put all the console history files in one place

 In mysql you can do
 export MSQL_HISTFILE=~/.history/mysql
 and the history file is created and stored

 I can so this with bash,python,postgres

 How can I do it with WGET in linux using the $HOME/.bashrc

 .wget-hsts was left in my home directory yesterday how can I export where it goes to

**Comment by jay** [comment]
This is my fork of the wget repo, you are asking in the wrong place. Subscribe and then post to the mailing list at https://lists.gnu.org/mailman/listinfo/bug-wget
